logs-enabled: true
storage:
  type: MySQL # available types: MySQL, PostgreSQL
  host: '127.0.0.1'
  port: 3306
  database: 'database'
  login: 'root'
  password: 'password'
servers:
  CoreServer:
    port: 2222
  FilesServer:
    port: 3333